language: node_js
node_js:
  - "0.10"

env:
  global:
    - secure: SiIKdb1EdnBmpWtEH6JewDtaMVuc1GCpS8MbRvhNVHn59h4Kut+yTkuEp5o3E9u9dXjOGculKHOjMrX6MiL9HWyABDaZik6sIu8+OJXTLOt1qrwvHzdNbBN8T80w30I8qUQJiaCoRjHlDv4w5tIso2AwuKbNNIUKYFEyAoAests=
    - secure: KKcXb/safftmMXKuSujQBiP3sgLkQ6x+K87dDgzlnWR9xfoHSrn/9DSdnxv3nyKLiFzKYtWcXK32XnAWc2luf61LaIBEiMe3I9EmKjvbJSqhD7Lni5MC9Gd/dmy8TzM+fdHkjWxUanqQfiqpRy3TLIW20AFxRyL9CMIDOz/h4g0=

addons:
  sauce_connect: true

script: grunt